import './styles.css';
type Cmd={id:string;category:string;title:string;description:string;command:string;tags:string[]};
const commands:Cmd[]=[
{id:'AI-001',category:'Marketing',title:'Product Gravity Finder',description:'Analyze what makes a product naturally attractive to its target customer.',command:'/gravityfying Analyze this product for customer gravity. Identify the strongest pain, desire, emotional trigger, product proof, objection, hook, demo angle, and CTA. Return a high-converting Filipino content direction without unsupported claims.',tags:['product','marketing','gravity']},
{id:'AI-002',category:'Product Research',title:'Affiliate Product Research',description:'Turn a product into a structured affiliate research brief.',command:'/researchproduct Research this product for affiliate marketing. Identify exact target customer, problem, features, benefits, objections, desires, competitors, proof signals, demo opportunities, hooks, content angles, and purchase-intent keywords. Separate verified facts from assumptions.',tags:['affiliate','research','product']},
{id:'AI-003',category:'Script',title:'5-Scene Sales Script',description:'Create one cohesive short-form video from five clips.',command:'/5scenescript Create one 5-scene vertical affiliate video. Each scene is approximately 10 seconds and continues one story for one target customer. Use Filipino dialogue, Hook → Problem → Demonstration → Benefit → CTA. CTA only in Scene 5. Avoid fake discounts, ratings, or unsupported claims.',tags:['script','tiktok','video']},
{id:'AI-004',category:'Image',title:'Product-Locked Image Prompt',description:'Generate scene prompts while protecting exact product identity.',command:'/productlock Create a vertical 9:16 commercial image prompt using the supplied product image as the absolute product source of truth. Preserve exact shape, silhouette, proportions, color, materials, buttons, ports, attachments, logos and markings. Do not redesign or invent product components.',tags:['image','product lock','prompt']},
{id:'AI-005',category:'Video',title:'Image-to-Video Product Lock',description:'Animate a supplied product scene without geometry drift.',command:'/animateproduct Animate the supplied scene image as the first-frame source of truth for a realistic 10-second vertical 9:16 video. Preserve product geometry and identity throughout. Use natural hand, eye and body motion, accurate lip sync, stable lighting, no flicker, warping, extra fingers, floating text or invented product details.',tags:['video','animation','product lock']},
{id:'AI-006',category:'Thumbnail',title:'High-Converting Thumbnail',description:'Create a mobile-first thumbnail concept with one clear message.',command:'/thumbnail Create a high-converting vertical 9:16 thumbnail for this content. Make the product or core subject instantly recognizable, use one target customer, strong emotional expression, premium commercial lighting and one bold Filipino headline that communicates the video message before playback. No random text or fake claims.',tags:['thumbnail','creative','hook']},
{id:'AI-007',category:'Marketing',title:'Customer Pain Mapper',description:'Map functional and emotional buying problems.',command:'/painmap Analyze this target customer. Separate surface problem, recurring frustration, emotional cost, failed alternatives, hidden objection, desired transformation, urgency trigger, and the exact language they are likely to use. Convert the findings into five content hooks.',tags:['customer','pain','hooks']},
{id:'AI-008',category:'Marketing',title:'Offer Builder',description:'Structure an offer around value instead of hype.',command:'/offerbuilder Build a credible offer for this product or service. Define audience, core outcome, mechanism, inclusions, proof needed, risk reducers, objections, price framing, ethical urgency, and CTA. Do not invent scarcity, guarantees, testimonials or results.',tags:['offer','sales','conversion']},
{id:'AI-009',category:'Script',title:'UGC Script Builder',description:'Natural creator-style short-form script.',command:'/ugcscript Write a natural Filipino UGC script for one target customer. Start with a believable situation, show the problem, introduce the product naturally, demonstrate the most relevant feature, explain the practical benefit, address one objection, and close with a soft CTA. Avoid exaggerated claims.',tags:['ugc','script','affiliate']},
{id:'AI-010',category:'Business',title:'Business Idea Validator',description:'Pressure-test an idea before spending heavily.',command:'/validatebusiness Evaluate this business idea using customer problem, willingness to pay, existing alternatives, differentiation, acquisition channel, delivery complexity, margins, repeatability, risks, fastest low-cost validation test, and clear go/no-go evidence.',tags:['business','validation','strategy']},
{id:'AI-011',category:'Content',title:'30-Day Content Engine',description:'Build a balanced content pipeline around one niche.',command:'/30daycontent Build a 30-day content plan for this niche. Balance education, problem awareness, demonstration, objection handling, authority, story, comparison and conversion. Give each day one topic, hook, format and CTA while avoiding repetitive angles.',tags:['content','calendar','strategy']},
{id:'AI-012',category:'SEO',title:'Short-Form SEO Pack',description:'Package a video for search and discovery.',command:'/seopack Create an SEO package for this short-form video: searchable title, concise description, primary keyword, supporting keywords, search intent, natural caption and four highly relevant hashtags. Avoid keyword stuffing.',tags:['seo','caption','keywords']},
{id:'AI-013',category:'Product Research',title:'Target Customer Split',description:'Find distinct audiences for the same product.',command:'/targetcustomers Identify five genuinely distinct target customers for this product. For each give context, primary pain, buying trigger, objection, strongest feature-benefit match, demonstration scenario and unique hook. Do not create superficial demographic variations.',tags:['customer','segmentation','product']},
{id:'AI-014',category:'Content',title:'Hook Generator',description:'Generate hooks from multiple psychological angles.',command:'/hooks Generate 20 short Filipino hooks for this topic using problem, curiosity, contrast, mistake, demonstration, identity, objection, consequence and transformation angles. Keep each hook specific, believable and suitable for the first 2 seconds.',tags:['hooks','content','filipino']},
{id:'AI-015',category:'Business',title:'Workflow Simplifier',description:'Turn a messy process into a repeatable system.',command:'/workflow Audit this workflow. Identify bottlenecks, duplicate work, manual steps, failure points, dependencies and unnecessary subscriptions. Redesign it into the simplest reliable sequence with clear inputs, outputs, statuses and automation opportunities.',tags:['workflow','operations','automation']}
];
const app=document.querySelector<HTMLDivElement>('#ai-library')!;let active='ALL',term='';
const cats=['ALL',...Array.from(new Set(commands.map(x=>x.category)))];
app.innerHTML=`<main class="min-h-screen bg-stone-950 text-stone-100"><header class="sticky top-0 z-20 border-b border-amber-500/20 bg-stone-950/95 backdrop-blur"><div class="mx-auto max-w-7xl px-4 py-4"><div class="flex items-center justify-between gap-3"><div><p class="text-xs font-black tracking-[.22em] text-amber-400">DELIONARYO AI SYSTEM</p><h1 class="text-xl font-black">AI DELIONARYO LIBRARY</h1></div><a href="/" class="rounded-xl border border-amber-500/30 px-3 py-2 text-sm font-black text-amber-300">HOME</a></div></div></header><div class="mx-auto max-w-7xl px-4 py-8"><section class="overflow-hidden rounded-3xl border border-amber-500/30 bg-gradient-to-br from-stone-900 to-stone-950 p-6 sm:p-8"><p class="text-sm font-black text-amber-400">COMMAND INTELLIGENCE LIBRARY</p><h2 class="mt-2 max-w-3xl text-3xl font-black sm:text-5xl">One command. Clear execution.</h2><p class="mt-3 max-w-2xl text-stone-400">Search DELIONARYO commands for marketing, product research, scripts, images, videos, thumbnails, SEO, content and business systems.</p><div class="mt-6 grid gap-3 sm:grid-cols-[1fr_auto]"><input id="search" class="rounded-2xl border border-stone-700 bg-stone-950 px-5 py-4 outline-none focus:border-amber-400" placeholder="Search command, problem, category or keyword…"><div class="rounded-2xl border border-amber-500/30 px-5 py-4 text-center"><b id="count" class="text-amber-400">${commands.length}</b><span class="ml-2 text-sm text-stone-400">commands</span></div></div></section><div id="cats" class="mt-5 flex gap-2 overflow-x-auto pb-2"></div><section id="grid" class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"></section></div></main>`;
const esc=(v:string)=>v.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m));
function render(){document.querySelector('#cats')!.innerHTML=cats.map(c=>`<button data-cat="${c}" class="whitespace-nowrap rounded-full border px-4 py-2 text-sm font-black ${c===active?'border-amber-400 bg-amber-400 text-stone-950':'border-stone-700 text-stone-300'}">${c}</button>`).join('');const q=term.toLowerCase(),items=commands.filter(x=>(active==='ALL'||x.category===active)&&(!q||[x.id,x.category,x.title,x.description,x.command,...x.tags].join(' ').toLowerCase().includes(q)));document.querySelector('#count')!.textContent=String(items.length);document.querySelector('#grid')!.innerHTML=items.length?items.map(x=>`<article class="flex flex-col rounded-2xl border border-stone-800 bg-stone-900/40 p-5"><div class="flex items-center justify-between gap-2"><span class="text-xs font-black tracking-widest text-amber-400">${x.id}</span><span class="rounded-full border border-stone-700 px-2.5 py-1 text-xs text-stone-400">${x.category}</span></div><h3 class="mt-3 text-xl font-black">${esc(x.title)}</h3><p class="mt-2 text-sm text-stone-400">${esc(x.description)}</p><div class="mt-4 flex-1 rounded-xl border border-stone-800 bg-stone-950 p-4 text-sm leading-6 text-stone-300">${esc(x.command)}</div><div class="mt-3 flex flex-wrap gap-1">${x.tags.map(t=>`<span class="text-xs text-stone-500">#${esc(t)}</span>`).join(' ')}</div><button data-copy="${x.id}" class="mt-4 w-full rounded-xl bg-amber-400 px-4 py-3 font-black text-stone-950">COPY COMMAND</button></article>`).join(''):`<div class="md:col-span-2 xl:col-span-3 rounded-2xl border border-stone-800 p-10 text-center text-stone-500">No matching command found.</div>`;document.querySelectorAll<HTMLButtonElement>('[data-cat]').forEach(b=>b.onclick=()=>{active=b.dataset.cat!;render()});document.querySelectorAll<HTMLButtonElement>('[data-copy]').forEach(b=>b.onclick=async()=>{const x=commands.find(c=>c.id===b.dataset.copy)!;await navigator.clipboard.writeText(x.command);const old=b.textContent;b.textContent='COPIED ✓';setTimeout(()=>b.textContent=old,1200)})}document.querySelector<HTMLInputElement>('#search')!.oninput=e=>{term=(e.target as HTMLInputElement).value;render()};render();