const AI_COMMANDS='https://delionaryo-video-uploader.vercel.app/ai-command-library';
const DIGITAL_LIBRARY='https://delionaryo-ebook-library.vercel.app';
const BUSINESS_CALCULATOR='https://delionaryo-business-calculator.vercel.app';
const LEARNING_CAMPUS='https://delionaryo-learning-campus.vercel.app';

const css=document.createElement('style');
css.textContent=`
#member-portal .campus-upgrade-mission{margin:24px 0;padding:26px;border:1px solid rgba(45,212,191,.28);border-radius:22px;background:linear-gradient(135deg,rgba(8,47,73,.9),rgba(13,78,86,.52));display:flex;align-items:center;justify-content:space-between;gap:24px;box-shadow:0 18px 55px rgba(0,0,0,.18)}
#member-portal .campus-upgrade-mission .mission-copy{max-width:720px}#member-portal .campus-upgrade-mission .mission-kicker{margin:0;color:#5eead4;font-size:11px;font-weight:900;letter-spacing:.16em}#member-portal .campus-upgrade-mission h2{margin:8px 0 7px;color:#f8fafc;font-size:clamp(25px,3vw,38px);line-height:1.05}#member-portal .campus-upgrade-mission p{margin:0;color:#a9c4cb;line-height:1.6}#member-portal .mission-count{min-width:190px;text-align:right}#member-portal .mission-count strong{display:block;color:#f8fafc;font-size:30px}#member-portal .mission-count span{color:#5eead4;font-size:11px;font-weight:800;letter-spacing:.08em}
#member-portal .campus-quick-access{margin:28px 0 10px}#member-portal .campus-quick-access>p{margin:0 0 12px;color:#5eead4;font-size:11px;font-weight:900;letter-spacing:.15em}#member-portal .quick-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}#member-portal .quick-btn{display:flex;align-items:center;gap:14px;min-height:82px;padding:17px 18px;border:1px solid #244653;border-radius:16px;background:#0b2230;color:#eaf7f8;text-decoration:none;transition:.18s ease}#member-portal .quick-btn:hover{transform:translateY(-2px);border-color:#2dd4bf;background:#0d2c38}#member-portal .quick-icon{width:40px;height:40px;display:grid;place-items:center;flex:0 0 40px;border-radius:11px;background:#103847;color:#5eead4;font-size:19px}#member-portal .quick-btn strong{display:block;font-size:14px}#member-portal .quick-btn small{display:block;margin-top:4px;color:#7899a4;font-size:10px}#member-portal .quick-arrow{margin-left:auto;color:#5eead4;font-weight:900}
#member-portal .course-open,#member-portal .available-open{border:1px solid #2dd4bf!important;border-radius:10px!important;background:#0c3a42!important;color:#7ff4e5!important;padding:11px 16px!important;font-weight:900!important;cursor:pointer!important;box-shadow:none!important}#member-portal .course-open:hover,#member-portal .available-open:hover{background:#0f4a53!important;color:#fff!important}
#member-portal .campus-nav .upgrade-nav{display:flex!important;align-items:center!important;width:100%;gap:10px;border:0;background:transparent;color:inherit;text-align:left;cursor:pointer}
@media(max-width:900px){#member-portal .quick-grid{grid-template-columns:1fr 1fr}#member-portal .campus-upgrade-mission{align-items:flex-start;flex-direction:column}#member-portal .mission-count{text-align:left}}@media(max-width:560px){#member-portal .quick-grid{grid-template-columns:1fr}}
`;
document.head.appendChild(css);

function addNav(nav:Element,label:string,icon:string,url:string){if([...nav.querySelectorAll('button,a')].some(x=>x.textContent?.includes(label)))return;const a=document.createElement('a');a.className='upgrade-nav';a.href=url;a.target='_blank';a.rel='noreferrer';a.innerHTML=`<span>${icon}</span><span>${label}</span>`;nav.appendChild(a)}
function quick(label:string,sub:string,icon:string,url:string){return `<a class="quick-btn" href="${url}" target="_blank" rel="noreferrer"><span class="quick-icon">${icon}</span><span><strong>${label}</strong><small>${sub}</small></span><span class="quick-arrow">→</span></a>`}
function upgrade(){const portal=document.querySelector('#member-portal');if(!portal||portal.getAttribute('data-professional-upgrade')==='1')return;portal.setAttribute('data-professional-upgrade','1');const nav=portal.querySelector('.campus-nav');if(nav){addNav(nav,'My Journey','◎',LEARNING_CAMPUS+'/#journey');addNav(nav,'DELIONARYO AI Coach','✦','https://delionaryo.vercel.app/#ai-coach');addNav(nav,'Digital Library','▤',DIGITAL_LIBRARY);addNav(nav,'AI Command Library','✣',AI_COMMANDS);addNav(nav,'Business Calculator','▦',BUSINESS_CALCULATOR)}
const hero=portal.querySelector('.campus-hero');if(hero){const mission=document.createElement('section');mission.className='campus-upgrade-mission';mission.innerHTML=`<div class="mission-copy"><p class="mission-kicker">DELIONARYO 1 MILLION GRADUATE PROGRAM</p><h2>Be One of One Million Graduates.</h2><p>Learn with direction, execute with discipline, build measurable evidence, and progress toward responsible financial stewardship.</p></div><div class="mission-count"><strong>1,000,000</strong><span>GRADUATE MISSION</span></div>`;hero.insertAdjacentElement('afterend',mission)}
const stats=portal.querySelector('.campus-stats');if(stats){const access=document.createElement('section');access.className='campus-quick-access';access.innerHTML=`<p>QUICK ACCESS · LEARN → EXECUTE → MULTIPLY</p><div class="quick-grid">${quick('AI Command Library','200 premium AI commands','✣',AI_COMMANDS)}${quick('Digital Library','Ebooks & transformation resources','▤',DIGITAL_LIBRARY)}${quick('Business Calculator','Business management & multiplication','▦',BUSINESS_CALCULATOR)}${quick('My Journey','Transformation progress','◎',LEARNING_CAMPUS+'/#journey')}${quick('AI Coach','Guidance & next action','✦','https://delionaryo.vercel.app/#ai-coach')}${quick('Learning Campus','Open full member campus','⌂',LEARNING_CAMPUS)}</div>`;stats.insertAdjacentElement('afterend',access)}
}
new MutationObserver(upgrade).observe(document.body,{childList:true,subtree:true});upgrade();