export type EnrollmentCourse={id:string;title:string;price:number};
const GCASH_NAME='Rodelio Legaspi';
const GCASH_NUMBER='0951 941 6959';

export function createPaymentCenter(course:EnrollmentCourse){
 document.querySelector('#enrollment-payment-center')?.remove();
 const panel=document.createElement('section');panel.id='enrollment-payment-center';panel.className='rounded-2xl border border-amber-500/30 bg-stone-950 p-5 md:p-6 h-full shadow-2xl';
 panel.innerHTML=`<div class="flex items-center justify-between gap-3"><div><p class="text-xs font-black tracking-[.22em] text-amber-400">DELIONARYO</p><h3 class="mt-1 text-xl font-black">PAYMENT CENTER</h3></div><span class="rounded-full border border-amber-500/30 bg-amber-500/10 px-3 py-1 text-xs font-black text-amber-300">SECURE ENROLLMENT</span></div>
 <div class="mt-5 rounded-2xl border border-stone-800 bg-stone-900 p-4"><p class="text-xs font-black tracking-widest text-amber-400">SELECTED COURSE</p><h4 class="mt-2 text-lg font-black">${course.title}</h4><p class="mt-1 text-xs text-stone-400">Practical AI content creation • One-time course access</p><div class="mt-4 flex items-end justify-between border-t border-stone-800 pt-4"><span class="text-sm text-stone-400">Total Payment</span><strong class="text-2xl text-amber-400">₱${course.price.toLocaleString()}.00</strong></div></div>
 <div class="mt-6"><p class="text-sm font-black">Choose Payment Method</p><div class="mt-3 grid grid-cols-3 gap-2"><button data-pay="gcash" class="rounded-xl border border-amber-400 bg-amber-400/10 p-3 text-center"><strong class="block text-sm">GCash</strong><span class="text-[10px] text-amber-300">AVAILABLE</span></button><button data-pay="maya" class="rounded-xl border border-stone-700 p-3 text-center opacity-60"><strong class="block text-sm">Maya</strong><span class="text-[10px] text-stone-500">COMING</span></button><button data-pay="bank" class="rounded-xl border border-stone-700 p-3 text-center opacity-60"><strong class="block text-sm">Bank</strong><span class="text-[10px] text-stone-500">COMING</span></button></div></div>
 <div id="payment-method-details" class="mt-4"></div>
 <div class="mt-5 rounded-xl border border-stone-800 bg-black/30 p-4"><div class="flex gap-3"><span class="text-amber-400">✓</span><div><p class="text-sm font-black">Payment Protection</p><p class="mt-1 text-xs leading-5 text-stone-400">Payment does not automatically create an account or unlock a course. DELIONARYO verifies the payment first, then sends your verification code manually by SMS or email.</p></div></div></div>`;return panel;
}

export function activatePaymentCenter(panel:HTMLElement){
 const details=panel.querySelector<HTMLElement>('#payment-method-details');
 const show=(method:string)=>{if(!details)return;
  if(method==='gcash')details.innerHTML=`<div class="rounded-2xl border border-amber-500/30 bg-gradient-to-br from-amber-500/10 to-stone-900 p-5"><div class="flex items-center justify-between"><p class="font-black text-amber-400">GCASH PAYMENT</p><span class="rounded-full bg-amber-400 px-2 py-1 text-[10px] font-black text-stone-950">ACTIVE</span></div><div class="mt-4 space-y-3"><div class="rounded-xl bg-stone-950 p-3"><p class="text-[10px] uppercase tracking-widest text-stone-500">Account Name</p><p class="mt-1 font-black">${GCASH_NAME}</p></div><div class="rounded-xl bg-stone-950 p-3"><p class="text-[10px] uppercase tracking-widest text-stone-500">GCash Number</p><div class="mt-1 flex items-center justify-between gap-3"><p class="font-black tracking-wide">${GCASH_NUMBER}</p><button id="copy-gcash" type="button" class="rounded-lg border border-amber-500/40 px-3 py-1 text-xs font-black text-amber-300">COPY</button></div></div></div><div class="mt-4 rounded-xl border border-stone-700 p-3"><p class="text-xs font-black text-stone-300">AFTER SENDING PAYMENT</p><p class="mt-1 text-xs leading-5 text-stone-400">Keep your GCash reference number. We will use it to verify your payment before your DELIONARYO verification code and account activation.</p></div></div>`;
  if(method==='maya')details.innerHTML='<div class="rounded-xl border border-stone-800 bg-stone-900 p-5"><p class="font-black">Maya</p><p class="mt-2 text-sm text-stone-400">Payment slot reserved. No Maya account details have been published yet.</p></div>';
  if(method==='bank')details.innerHTML='<div class="rounded-xl border border-stone-800 bg-stone-900 p-5"><p class="font-black">Bank Transfer</p><p class="mt-2 text-sm text-stone-400">Payment slot reserved. No bank account details have been published yet.</p></div>';
  panel.querySelector<HTMLButtonElement>('#copy-gcash')?.addEventListener('click',async(e)=>{try{await navigator.clipboard.writeText('09519416959');(e.currentTarget as HTMLButtonElement).textContent='COPIED'}catch{(e.currentTarget as HTMLButtonElement).textContent='09519416959'}});
 };
 panel.querySelectorAll<HTMLButtonElement>('[data-pay]').forEach(button=>button.addEventListener('click',()=>show(button.dataset.pay||'gcash')));show('gcash');
}