import './styles.css';
import './learningAuth';
import {createPaymentCenter,activatePaymentCenter} from './enrollmentCenter';
import {markEnrollmentIntent} from './enrollmentAuthBridge';

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<main class="min-h-screen bg-stone-950 text-stone-100"><header class="sticky top-0 z-20 border-b border-amber-500/20 bg-stone-950/95 backdrop-blur"><div class="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between"><a href="#top" class="font-black tracking-wider text-amber-400 text-sm sm:text-base">DELIONARYO</a><div class="flex items-center gap-3"><button id="header-enrollment" class="text-xs sm:text-sm font-black text-amber-300">ENROLLMENT</button><button id="header-login" class="rounded-xl border border-amber-400 px-4 py-2 text-xs sm:text-sm font-black text-amber-300">LOGIN</button></div></div></header>
<section id="top" class="relative overflow-hidden"><div class="absolute inset-0 bg-gradient-to-br from-amber-950/40 via-stone-950 to-stone-950"></div><div class="relative max-w-7xl mx-auto px-5 py-20 md:py-28"><div class="max-w-4xl"><div class="inline-flex rounded-full border border-amber-500/30 bg-amber-500/10 px-4 py-2 text-sm font-bold text-amber-300">DELIONARYO TRANSFORMATION PLATFORM</div><h1 class="mt-7 text-5xl md:text-7xl font-black leading-[.95]">Be One in a Million.<br><span class="text-amber-400">Graduate From Poverty.</span></h1><p class="mt-6 max-w-3xl text-lg md:text-xl text-stone-300 leading-8">Start with free financial education. Enroll when you are ready to continue inside the DELIONARYO Learning Campus.</p><div class="mt-8 flex flex-wrap gap-3"><a href="#free-training" class="inline-flex rounded-xl bg-amber-400 px-7 py-4 font-black text-stone-950">START FREE →</a><button id="hero-enrollment" class="inline-flex rounded-xl border border-stone-700 px-7 py-4 font-black">ENROLLMENT →</button></div></div></div></section>
<section id="free-training" class="border-y border-amber-500/20 bg-stone-900"><div class="max-w-5xl mx-auto px-5 py-14"><div class="text-center max-w-3xl mx-auto"><p class="text-amber-400 font-black tracking-widest text-sm">FREE TRAINING + FREE EBOOK</p><h2 class="mt-2 text-3xl md:text-5xl font-black">Start your M.O.N.E.Y'S Transformation free.</h2><p class="mt-4 text-stone-400 text-lg">Watch the free DELIONARYO financial training, then enter your details to unlock the free eBook.</p></div><div class="mt-8 max-w-4xl mx-auto aspect-video rounded-2xl overflow-hidden border border-amber-500/30 bg-black"><iframe class="w-full h-full" src="https://www.youtube.com/embed/5mcipwXpMgk" title="DELIONARYO Free Financial Training" loading="lazy" allowfullscreen></iframe></div><div class="mt-9 grid md:grid-cols-2 gap-8"><div><p class="text-amber-400 font-black tracking-widest text-sm">CLAIM YOUR FREE EBOOK</p><h3 class="mt-2 text-3xl font-black">Continue after the free training.</h3><p class="mt-3 text-stone-400">Enter your first name and email to unlock your free Financial Transformation Guide.</p></div><form class="rounded-2xl border border-stone-700 bg-stone-950 p-5 space-y-4"><input id="lead-name" required placeholder="First Name" class="w-full rounded-xl border border-stone-700 bg-stone-900 px-4 py-3"><input id="lead-email" type="email" required placeholder="Email" class="w-full rounded-xl border border-stone-700 bg-stone-900 px-4 py-3"><button id="lead-submit" type="button" class="w-full rounded-xl bg-amber-400 px-6 py-4 font-black text-stone-950">GET MY FREE EBOOK</button><p id="lead-message" class="text-sm text-stone-400">Your information is used to deliver your free eBook and educational updates.</p><div id="ebook-unlock" class="hidden"><a href="https://drive.google.com/file/d/1pDY964J6RvBxeHSPURgsfmmzMhhmco5m/view?usp=drivesdk" target="_blank" class="text-amber-400 font-black">OPEN FREE EBOOK →</a></div></form></div></div></section>
<section id="enrollment-info" class="max-w-7xl mx-auto px-4 sm:px-5 py-16"><div class="text-center"><p class="text-amber-400 font-black tracking-widest text-sm">DELIONARYO ENROLLMENT</p><h2 class="mt-2 text-3xl md:text-5xl font-black">Enroll in Your Course</h2><p class="mt-3 text-stone-400">Complete payment first. Your learner account is created after payment verification.</p></div><div class="mx-auto mt-7 grid max-w-3xl grid-cols-3 gap-2 text-center text-xs sm:text-sm"><div class="border-b-2 border-amber-400 p-3 font-black text-amber-300">① Payment</div><div class="p-3 text-stone-400">② Verification</div><div class="p-3 text-stone-400">③ Create Account</div></div><div class="mt-6 grid lg:grid-cols-2 gap-4"><section class="rounded-2xl border border-amber-500/30 bg-stone-950 p-5 md:p-6"><p class="font-black tracking-wide text-amber-400">ENROLLMENT INFORMATION</p><p class="mt-4 text-sm text-stone-400">Enter the email you want connected to your future learner account. Do not create a password yet.</p><label class="mt-5 block"><span class="text-sm font-bold">Email address</span><input id="enroll-email" type="email" placeholder="name@example.com" class="mt-2 w-full rounded-xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none focus:border-amber-400"></label><label class="mt-4 block"><span class="text-sm font-bold">Full name</span><input id="enroll-name" placeholder="Your full name" class="mt-2 w-full rounded-xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none focus:border-amber-400"></label><p class="mt-5 rounded-xl border border-stone-800 bg-stone-900 p-4 text-xs text-stone-400">After payment verification, you will complete your learner account and set your password. We do not hold an unactivated password while payment is pending.</p><button id="section-enrollment" class="mt-5 w-full rounded-xl bg-amber-400 px-6 py-4 font-black text-stone-950">PROCEED TO PAYMENT →</button><p class="mt-5 text-center text-sm text-stone-400">Already have an account? <button id="enrollment-login" class="font-black text-amber-400">Login</button></p></section><div id="payment-center-host"></div></div><p id="enrollment-copy" class="mt-5 text-center text-sm text-stone-500">Payment submission is for verification. It does not automatically activate course access.</p></section>
<div id="books" class="hidden" aria-hidden="true"></div><footer class="border-t border-stone-800"><div class="max-w-7xl mx-auto px-5 py-10 text-center text-sm text-stone-500">DELIONARYO TRANSFORMATION PLATFORM</div></footer></main>`;
const waitFor=(s:string,d:(e:HTMLButtonElement)=>void,t=40)=>{const e=document.querySelector<HTMLButtonElement>(s);if(e){d(e);return;}if(t>0)setTimeout(()=>waitFor(s,d,t-1),100)};
const enrollment=()=>document.querySelector('#enrollment-info')?.scrollIntoView({behavior:'smooth',block:'start'});
const login=()=>waitFor('#learning-login',b=>b.click());
document.querySelector('#header-enrollment')?.addEventListener('click',enrollment);document.querySelector('#hero-enrollment')?.addEventListener('click',enrollment);document.querySelector('#header-login')?.addEventListener('click',login);document.querySelector('#enrollment-login')?.addEventListener('click',login);
const host=document.querySelector<HTMLElement>('#payment-center-host');if(host){const panel=createPaymentCenter({id:'AI-CONTENT-499',title:'AI Content Creation Tutorial',price:499});host.appendChild(panel);activatePaymentCenter(panel);}
document.querySelector('#section-enrollment')?.addEventListener('click',()=>{const email=document.querySelector<HTMLInputElement>('#enroll-email');const name=document.querySelector<HTMLInputElement>('#enroll-name');if(!email?.value||!email.checkValidity()){email?.reportValidity();return}if(!name?.value.trim()){name?.focus();return}markEnrollmentIntent();host?.scrollIntoView({behavior:'smooth',block:'center'});const copy=document.querySelector<HTMLElement>('#enrollment-copy');if(copy)copy.textContent='Payment step ready. Use the selected payment method and keep your reference number for verification.';});
const removeDuplicateLogin=()=>document.querySelector<HTMLButtonElement>('#learning-login-top')?.remove();setTimeout(removeDuplicateLogin,250);setTimeout(removeDuplicateLogin,1000);
const submit=document.querySelector<HTMLButtonElement>('#lead-submit');submit?.addEventListener('click',()=>{const name=document.querySelector<HTMLInputElement>('#lead-name');const email=document.querySelector<HTMLInputElement>('#lead-email');const msg=document.querySelector<HTMLElement>('#lead-message');const unlock=document.querySelector<HTMLElement>('#ebook-unlock');if(!name?.value.trim()){name?.reportValidity();return}if(!email?.checkValidity()){email?.reportValidity();return}if(msg)msg.textContent=`Thanks, ${name.value.trim()}. Your free eBook is ready.`;unlock?.classList.remove('hidden')});