import './styles.css';
import './learningAuth';

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<main class="min-h-screen bg-stone-950 text-stone-100">
<header class="sticky top-0 z-20 border-b border-amber-500/20 bg-stone-950/95 backdrop-blur"><div class="max-w-7xl mx-auto px-5 h-16 flex items-center justify-between"><a href="#top" class="font-black tracking-widest text-amber-400">DELIONARYO</a><div class="flex items-center gap-3"><button id="header-enrollment" class="text-sm font-black text-amber-300 hover:text-amber-400 transition">ENROLLMENT</button><button id="header-login" class="rounded-xl border border-amber-400 px-4 py-2 text-sm font-black text-amber-300">LOGIN</button></div></div></header>
<section id="top" class="relative overflow-hidden"><div class="absolute inset-0 bg-gradient-to-br from-amber-950/40 via-stone-950 to-stone-950"></div><div class="relative max-w-7xl mx-auto px-5 py-20 md:py-28"><div class="max-w-4xl"><div class="inline-flex rounded-full border border-amber-500/30 bg-amber-500/10 px-4 py-2 text-sm font-bold text-amber-300">DELIONARYO TRANSFORMATION PLATFORM</div><h1 class="mt-7 text-5xl md:text-7xl font-black leading-[.95]">Be One in a Million.<br><span class="text-amber-400">Graduate From Poverty.</span></h1><p class="mt-6 max-w-3xl text-lg md:text-xl text-stone-300 leading-8">Start with free financial education. When you are ready for structured paid learning, enroll and build your DELIONARYO learner account.</p><div class="mt-8 flex flex-wrap gap-3"><a href="#free-training" class="inline-flex rounded-xl bg-amber-400 px-7 py-4 font-black text-stone-950">START FREE →</a><button id="hero-enrollment" class="inline-flex rounded-xl border border-stone-700 px-7 py-4 font-black">ENROLLMENT →</button></div></div></div></section>
<section id="free-training" class="border-y border-amber-500/20 bg-stone-900"><div class="max-w-5xl mx-auto px-5 py-14"><div class="text-center max-w-3xl mx-auto"><p class="text-amber-400 font-black tracking-widest text-sm">FREE TRAINING + FREE EBOOK</p><h2 class="mt-2 text-3xl md:text-5xl font-black">Start your M.O.N.E.Y'S Transformation free.</h2><p class="mt-4 text-stone-400 text-lg">Watch the free DELIONARYO financial training, then enter your details to unlock the free eBook.</p></div><div class="mt-8 max-w-4xl mx-auto aspect-video rounded-2xl overflow-hidden border border-amber-500/30 bg-black shadow-2xl"><iframe class="w-full h-full" src="https://www.youtube.com/embed/5mcipwXpMgk" title="DELIONARYO Free Financial Training" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="mt-9 grid md:grid-cols-2 gap-8 items-start"><div><p class="text-amber-400 font-black tracking-widest text-sm">CLAIM YOUR FREE EBOOK</p><h3 class="mt-2 text-3xl font-black">Continue after the free training.</h3><p class="mt-3 text-stone-400 leading-7">Enter your first name and email to unlock your free Financial Transformation Guide.</p></div><form class="rounded-2xl border border-stone-700 bg-stone-950 p-5 space-y-4"><label class="block"><span class="text-sm font-bold">First Name</span><input id="lead-name" required maxlength="100" autocomplete="given-name" class="mt-2 w-full rounded-xl border border-stone-700 bg-stone-900 px-4 py-3 text-stone-100 outline-none focus:border-amber-400"></label><label class="block"><span class="text-sm font-bold">Email</span><input id="lead-email" type="email" required maxlength="320" autocomplete="email" class="mt-2 w-full rounded-xl border border-stone-700 bg-stone-900 px-4 py-3 text-stone-100 outline-none focus:border-amber-400"></label><button id="lead-submit" type="button" class="w-full rounded-xl bg-amber-400 px-6 py-4 font-black text-stone-950">GET MY FREE EBOOK</button><p id="lead-message" class="text-sm text-stone-400">Your information is used to deliver your free eBook and DELIONARYO educational updates.</p><div id="ebook-unlock" class="hidden rounded-xl border border-amber-500/30 bg-amber-400/10 p-4"><p class="font-bold text-amber-300">Your free eBook is unlocked.</p><a href="https://drive.google.com/file/d/1pDY964J6RvBxeHSPURgsfmmzMhhmco5m/view?usp=drivesdk" target="_blank" rel="noopener noreferrer" class="mt-3 inline-block rounded-xl bg-amber-400 px-5 py-3 font-black text-stone-950">OPEN FREE EBOOK</a></div></form></div></div></section>
<section id="enrollment-info" class="max-w-7xl mx-auto px-5 py-20"><div class="rounded-3xl border border-amber-500/30 bg-gradient-to-br from-stone-900 to-amber-950/20 p-7 md:p-10"><p class="text-amber-400 font-black tracking-widest text-sm">DELIONARYO ENROLLMENT</p><h2 class="mt-3 text-4xl md:text-5xl font-black">Create your learner account.</h2><p class="mt-5 max-w-3xl text-stone-400 text-lg leading-8">Enrollment is the entry point for structured paid learning. Once registered, use Login to return to your private E-Learning Hub, available programs and courses you own.</p><button id="section-enrollment" class="mt-7 rounded-xl bg-amber-400 px-7 py-4 font-black text-stone-950">START ENROLLMENT →</button></div></section>
<footer class="border-t border-stone-800"><div class="max-w-7xl mx-auto px-5 py-10 text-center text-sm text-stone-500"><p class="font-black tracking-widest text-stone-300">DELIONARYO TRANSFORMATION PLATFORM</p><p class="mt-2">Free education • E-Learning • Execution • Stewardship</p><p class="mt-5">Educational content only. Individual results vary.</p></div></footer></main>`;

const enrollment=()=>{const register=document.querySelector<HTMLButtonElement>('#learning-register-button');if(register){register.click();return;}document.querySelector('#enrollment-info')?.scrollIntoView({behavior:'smooth'});};
const login=()=>{const button=document.querySelector<HTMLButtonElement>('#learning-login-button')||document.querySelector<HTMLButtonElement>('#learning-account-button');button?.click();};
document.querySelector('#header-enrollment')?.addEventListener('click',enrollment);document.querySelector('#hero-enrollment')?.addEventListener('click',enrollment);document.querySelector('#section-enrollment')?.addEventListener('click',enrollment);document.querySelector('#header-login')?.addEventListener('click',login);
const submit=document.querySelector<HTMLButtonElement>('#lead-submit');submit?.addEventListener('click',()=>{const name=document.querySelector<HTMLInputElement>('#lead-name');const email=document.querySelector<HTMLInputElement>('#lead-email');const message=document.querySelector<HTMLElement>('#lead-message');const unlock=document.querySelector<HTMLElement>('#ebook-unlock');if(!name||!email||!message||!unlock)return;if(!name.value.trim()){name.reportValidity();return;}if(!email.checkValidity()){email.reportValidity();return;}message.textContent=`Thanks, ${name.value.trim()}. Your free eBook is ready.`;unlock.classList.remove('hidden');});