const JOURNEY_ID='delionaryo-journey-campus';

function buildJourneyCampus(){
  const portal=document.querySelector<HTMLElement>('#member-portal');
  const main=portal?.querySelector<HTMLElement>('.campus-main');
  const nav=portal?.querySelector<HTMLElement>('.campus-nav');
  if(!portal||!main||!nav||document.querySelector(`#${JOURNEY_ID}`)) return false;
  const firstSection=main.querySelector('.campus-hero,.campus-stats,.campus-section');
  const journey=document.createElement('section'); journey.id=JOURNEY_ID; journey.className='journey-command-center';
  journey.innerHTML=`<div class="journey-hero"><div class="journey-hero-copy"><p class="journey-kicker">DELIONARYO PRIVATE TRANSFORMATION CAMPUS</p><h1>Journey to <span>1,000,000</span> Graduates</h1><p>Learn the system. Execute the plan. Measure real progress. Build financial stability and advance toward verified graduation.</p><div class="journey-actions"><button data-journey-scroll="journey-path">CONTINUE MY JOURNEY →</button></div></div><div class="mission-orbit"><small>MISSION</small><strong>1M</strong><span>VERIFIED GRADUATES</span><i>Progress is earned through verified completion—not registration alone.</i></div></div><div class="journey-metrics"><article><small>MY JOURNEY</small><strong>START</strong><span>Build your first verified milestone</span></article><article><small>LEARNING STATUS</small><strong>ACTIVE</strong><span>Continue your transformation curriculum</span></article><article><small>GRADUATE STATUS</small><strong>IN PROGRESS</strong><span>Complete learning + execution evidence</span></article></div><div id="journey-path" class="journey-panel"><div class="journey-heading"><div><p class="journey-kicker">YOUR TRANSFORMATION PATH</p><h2>Learn → Apply → Measure → Build → Graduate</h2></div><span class="journey-badge">VERIFIED JOURNEY</span></div><div class="journey-steps"><article><b>01</b><h3>Learn</h3><p>Complete your enrolled financial education and core lessons.</p></article><article><b>02</b><h3>Apply</h3><p>Turn lessons into consistent financial actions.</p></article><article><b>03</b><h3>Measure</h3><p>Track habits, milestones and evidence of progress.</p></article><article><b>04</b><h3>Build</h3><p>Strengthen financial capacity and stewardship.</p></article><article><b>05</b><h3>Graduate</h3><p>Meet defined completion criteria before entering the mission count.</p></article></div></div><div class="graduate-panel"><div><p class="journey-kicker">GRADUATION STANDARD</p><h2>Progress before prestige.</h2><p>A DELIONARYO graduate represents completed learning plus verified execution milestones. Purchases, registrations and logins alone do not count as graduation.</p></div><div class="graduate-checks"><span>✓ Learning completion</span><span>✓ Financial execution</span><span>✓ Progress evidence</span><span>✓ Defined milestone review</span></div></div>`;
  if(firstSection) main.insertBefore(journey,firstSection); else main.appendChild(journey);
  nav.querySelectorAll('button').forEach(b=>b.classList.remove('active'));
  const myJourney=document.createElement('button');myJourney.className='active';myJourney.innerHTML='◎ <span>My Journey</span>';myJourney.onclick=()=>journey.scrollIntoView({behavior:'smooth'});nav.prepend(myJourney);
  const dpbs=document.createElement('button');dpbs.innerHTML='◈ <span>Personal Banking</span>';dpbs.onclick=()=>openDPBS();myJourney.insertAdjacentElement('afterend',dpbs);
  const graduate=document.createElement('button');graduate.innerHTML='✦ <span>Graduate Status</span>';graduate.onclick=()=>journey.querySelector('.graduate-panel')?.scrollIntoView({behavior:'smooth'});nav.appendChild(graduate);
  journey.querySelectorAll<HTMLElement>('[data-journey-scroll]').forEach(btn=>btn.onclick=()=>document.querySelector(`#${btn.dataset.journeyScroll}`)?.scrollIntoView({behavior:'smooth'})); return true;
}

function openDPBS(){
  document.querySelector('#dpbs-private-view')?.remove();
  const portal=document.querySelector<HTMLElement>('#member-portal'); if(!portal)return;
  const view=document.createElement('div');view.id='dpbs-private-view';view.className='dpbs-private-overlay';
  view.innerHTML=`<div class="dpbs-private-shell"><header><div><p class="journey-kicker">DELIONARYO PERSONAL BANKING SYSTEM</p><h1>Be Your Own Personal Bank.</h1></div><button id="dpbs-close">← BACK TO CAMPUS</button></header><section class="dpbs-cycle"><article><span>01</span><h2>SAVE</h2><p>Build your own personal bank capital.</p></article><b>→</b><article><span>02</span><h2>BORROW</h2><p>Borrow from your own accumulated reserve.</p></article><b>→</b><article><span>03</span><h2>PAY + INTEREST</h2><p>Repay principal plus your internal interest.</p></article><b>→</b><article><span>04</span><h2>COMPOUND</h2><p>Return growth to your reserve and repeat the cycle.</p></article></section><section class="dpbs-ledger"><p class="journey-kicker">PERSONAL BANK LEDGER</p><h2>Your money works inside your own system.</h2><div><article><small>TOTAL SAVED</small><strong>₱0.00</strong></article><article><small>AVAILABLE BANK CAPITAL</small><strong>₱0.00</strong></article><article><small>OUTSTANDING BORROWED</small><strong>₱0.00</strong></article><article><small>PRINCIPAL REPAID</small><strong>₱0.00</strong></article><article><small>INTEREST RETURNED</small><strong>₱0.00</strong></article><article><small>CURRENT BANK VALUE</small><strong>₱0.00</strong></article></div><p class="dpbs-note">Foundation interface only. Transaction recording, repayment schedules and compounding calculations will be connected as the DPBS ledger is built.</p></section></div>`;
  portal.appendChild(view);view.querySelector('#dpbs-close')?.addEventListener('click',()=>view.remove());
}
const observer=new MutationObserver(()=>{if(buildJourneyCampus()) observer.disconnect()});observer.observe(document.documentElement,{childList:true,subtree:true});buildJourneyCampus();
