import { createClient } from '@supabase/supabase-js';
import './styles.css';

const supabase=createClient('https://tordvwlrtwxlbuuzgklt.supabase.co','sb_publishable_s_trbtJvrqcTxDBs_7yyTg_57wHs3sW');
const app=document.querySelector<HTMLDivElement>('#app')!;

function shell(){app.innerHTML=`<main class="shell"><header><div><small>DELIONARYO</small><h1>Dreamer Consultant</h1><p>Diagnose the problem. Recommend the next learning resource. Execute with clarity.</p></div><button id="logout" hidden>LOG OUT</button></header><section id="auth" class="card"><h2>Member Access</h2><p>Use your DELIONARYO member account.</p><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><button id="login">LOGIN</button><p id="auth-msg"></p></section><section id="workspace" class="workspace" hidden><article class="card"><small>CONSULTATION</small><h2>What problem are you trying to solve?</h2><textarea id="problem" rows="5" placeholder="Describe your current challenge..."></textarea><button id="analyze">ANALYZE MY NEXT STEP</button><p id="diagnosis"></p></article><article class="card"><small>RECOMMENDED RESOURCE</small><div id="recommendation"><p>Your recommendation will appear here.</p></div></article><article class="card"><small>RECENT CONTEXT</small><div id="recent"></div></article></section></main>`}

function words(v:string){return v.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)}
function score(item:any,problem:string){const hay=[...(item.problem_tags||[]),...(item.skill_tags||[]),item.journey_stage||'',item.learning_outcome||''].join(' ').toLowerCase();return words(problem).reduce((n,w)=>n+(hay.includes(w)?1:0),0)}

async function load(){const {data:{session}}=await supabase.auth.getSession();const auth=document.querySelector<HTMLElement>('#auth')!,workspace=document.querySelector<HTMLElement>('#workspace')!,logout=document.querySelector<HTMLButtonElement>('#logout')!;if(!session){auth.hidden=false;workspace.hidden=true;logout.hidden=true;return}auth.hidden=true;workspace.hidden=false;logout.hidden=false;const {data,error}=await supabase.rpc('get_my_dreamer_consultant_context');if(error){document.querySelector('#recent')!.textContent='Unable to load consultant context.';return}(window as any).__dreamer=data;const recent=(data?.recent_recommendations||[]).slice(0,5);document.querySelector('#recent')!.innerHTML=recent.length?recent.map((r:any)=>`<div class="recent"><b>${r.problem_summary||'Consultation'}</b><span>${r.diagnosis||''}</span></div>`).join(''):'<p>No recent consultation yet.</p>'}

shell();
document.querySelector('#login')?.addEventListener('click',async()=>{const email=(document.querySelector('#email') as HTMLInputElement).value.trim();const password=(document.querySelector('#password') as HTMLInputElement).value;const msg=document.querySelector('#auth-msg')!;msg.textContent='Signing in...';const {error}=await supabase.auth.signInWithPassword({email,password});msg.textContent=error?error.message:'';if(!error)load()});
document.querySelector('#logout')?.addEventListener('click',async()=>{await supabase.auth.signOut();load()});
document.querySelector('#analyze')?.addEventListener('click',()=>{const problem=(document.querySelector('#problem') as HTMLTextAreaElement).value.trim();if(!problem)return;const ctx=(window as any).__dreamer||{};const catalog=[...(ctx.catalog||[])].sort((a:any,b:any)=>score(b,problem)-score(a,problem));const best=catalog[0];document.querySelector('#diagnosis')!.textContent='Focus on one concrete problem, then apply the next relevant learning resource before adding another.';document.querySelector('#recommendation')!.innerHTML=best?`<h3>${best.title}</h3><p>${best.learning_outcome||'Recommended from your DELIONARYO learning catalog.'}</p><div class="meta"><span>${best.type||'RESOURCE'}</span><span>${best.owned?'OWNED':'AVAILABLE'}</span></div>`:'<p>No matching resource is available yet.</p>'});
supabase.auth.onAuthStateChange(()=>load());
load();
