import './styles.css';
import './portal';
import('./delionaryoAICoach').then(({ mountAICoach }) => mountAICoach());
const pay='https://pm.link/org-X97pkZ9v7uKBjxNAvYsmuL37/ttJb7q0';
const youtube='https://www.youtube.com/channel/UC8tBAhLFySPo7vp9cBUh4fA';
const tiktok='https://www.tiktok.com/@rrl6980?_r=1&_t=ZS-98clQNSR9KH';
const facebook='https://www.facebook.com/Delionaryo09';
const businessCalculator='https://delionaryo-business-calculator.vercel.app';
const marketplace='https://delionaryo-marketplace.vercel.app';
const app=document.querySelector<HTMLDivElement>('#app')!;
const lessons=[{id:'2KNvsRzkrZE',label:'EXCLUSIVE LESSON 01',title:'DELIONARYO Transformation Lesson 1'},{id:'0Y22DDoZQu0',label:'EXCLUSIVE LESSON 02',title:'DELIONARYO Transformation Lesson 2'},{id:'VyqE80DtCCs',label:'EXCLUSIVE LESSON 03',title:'DELIONARYO Transformation Lesson 3'}];
const days=[{day:'MONDAY',theme:'POOR',title:'See the System',learn:'Identify one money pattern keeping you in survival mode.',action:'Write one expense, habit, or decision you will change this week.'},{day:'TUESDAY',theme:'BLIND',title:'Gain Financial Clarity',learn:'Look clearly at where your money comes from and where it goes.',action:'Record today’s income and every expense.'},{day:'WEDNESDAY',theme:'SLAVE',title:'Break the Cycle',learn:'Recognize obligations and habits that control your choices.',action:'Choose one unnecessary financial obligation to reduce or remove.'},{day:'THURSDAY',theme:'OPPRESSED',title:'Build Capacity',learn:'Transformation grows when knowledge becomes useful skill and action.',action:'Spend 20 focused minutes improving one income-producing skill.'},{day:'FRIDAY',theme:'KINGDOM',title:'Practice Stewardship',learn:'Treat resources as something to manage wisely, intentionally, and responsibly.',action:'Set aside a portion of today’s resources before spending the rest.'},{day:'SATURDAY',theme:'ACTION',title:'Execute the Plan',learn:'Progress requires measurable execution, not information alone.',action:'Complete one financial task you have been postponing.'},{day:'SUNDAY',theme:'REFLECTION',title:'Measure and Improve',learn:'Review creates awareness; awareness improves the next decision.',action:'Write one win, one lesson, and one adjustment for next week.'}];
const saved=JSON.parse(localStorage.getItem('delionaryo-week')||'{}') as Record<string,boolean>;
const journeyCards=days.map((d,i)=>`<article class="journey-card ${saved[d.day]?'completed':''}" data-day="${d.day}"><div class="journey-top"><span>DAY ${i+1}</span><b>${d.day} · ${d.theme}</b></div><h3>${d.title}</h3><div class="lesson"><strong>LEARN</strong><p>${d.learn}</p></div><div class="lesson"><strong>ACTION</strong><p>${d.action}</p></div><button class="complete-btn" data-complete="${d.day}">${saved[d.day]?'✓ COMPLETED':'MARK COMPLETE'}</button></article>`).join('');
const lessonButtons=lessons.map((lesson,index)=>`<button data-video-index="${index}" class="video-select w-full rounded-2xl border border-white/10 bg-stone-950 p-5 text-left transition hover:border-amber-400/50"><span class="text-xs font-black tracking-widest text-amber-400">${lesson.label}</span><h3 class="mt-2 text-lg font-black">${lesson.title}</h3><p class="mt-2 text-sm text-stone-400">Play inside DELIONARYO →</p></button>`).join('');
app.innerHTML=`<main class="min-h-screen bg-stone-950 text-stone-100"><nav class="sticky top-0 z-50 border-b border-white/10 bg-stone-950/90 backdrop-blur"><div class="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="#top" class="font-black tracking-[.18em] text-amber-400">DELIONARYO</a><div class="hidden gap-6 text-sm font-bold text-stone-300 md:flex"><a href="#ai-portal">AI PORTAL</a><a href="#system">SYSTEM</a><a href="#journey">JOURNEY</a><a href="#learning">CAMPUS</a><a href="#execution-tools">EXECUTE</a><a href="#store">EBOOK</a></div><a href="#learning" class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-black text-stone-950">LEARNING CAMPUS</a></div></nav>
<section id="top" class="hero-grid border-b border-white/10"><div class="mx-auto max-w-6xl px-5 py-24 md:py-32"><p class="inline-flex rounded-full border border-amber-400/30 bg-amber-400/10 px-4 py-2 text-xs font-black tracking-widest text-amber-300">DELIONARYO TRANSFORMATION PLATFORM</p><h1 class="mt-7 max-w-5xl text-5xl font-black leading-[.95] md:text-7xl">Be One in a Million.<br><span class="text-amber-400">Graduate From Poverty.</span></h1><p class="mt-7 max-w-2xl text-lg leading-8 text-stone-300">Learn, execute, measure your results, and grow in stewardship. A practical transformation platform built to help Filipinos move from survival toward stability, ownership, and sovereignty.</p></div></section>
<section id="system" class="border-y border-white/10 bg-stone-900/40"><div class="mx-auto max-w-6xl px-5 py-20"><p class="text-xs font-black tracking-[.25em] text-amber-400">THE TRANSFORMATION SYSTEM</p><h2 class="mt-4 text-4xl font-black">M.O.N.E.Y Transformation</h2><div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div class="step"><span>M</span><b>Mind</b><p>Transform how you think.</p></div><div class="step"><span>O</span><b>Orientation</b><p>Align heart and direction.</p></div><div class="step"><span>N</span><b>Narrative</b><p>Change the words and story.</p></div><div class="step"><span>E</span><b>Execution</b><p>Move through disciplined action.</p></div><div class="step"><span>Y</span><b>Yield</b><p>Measure real results.</p></div></div></div></section>
<section id="journey" class="mx-auto max-w-6xl px-5 py-20"><p class="text-xs font-black tracking-[.25em] text-amber-400">7-DAY TRANSFORMATION JOURNEY</p><h2 class="mt-4 text-4xl font-black md:text-5xl">Learn. Act. Complete. Measure.</h2><div class="journey-grid">${journeyCards}</div></section>
<section id="learning" class="border-y border-white/10 bg-stone-900/40"><div class="mx-auto max-w-6xl px-5 py-20"><p class="text-xs font-black tracking-[.25em] text-amber-400">DELIONARYO LEARNING CAMPUS</p><h2 class="mt-4 text-4xl font-black md:text-5xl">Learn here. Execute in the ecosystem.</h2><p class="mt-4 max-w-3xl leading-7 text-stone-400">The Campus is the learning bridge. After each lesson, members can move directly into practical DELIONARYO execution tools.</p><div class="mt-10 grid gap-6 lg:grid-cols-[2fr_1fr]"><div class="overflow-hidden rounded-3xl border border-amber-400/20 bg-black"><div class="relative w-full" style="padding-top:56.25%"><iframe id="learning-player" class="absolute inset-0 h-full w-full" src="https://www.youtube-nocookie.com/embed/${lessons[0].id}?rel=0&playsinline=1" title="DELIONARYO Learning Campus" allowfullscreen></iframe></div><div class="p-6"><span id="lesson-label" class="text-xs font-black tracking-widest text-amber-400">${lessons[0].label}</span><h3 id="lesson-title" class="mt-2 text-2xl font-black">${lessons[0].title}</h3></div></div><div class="space-y-3">${lessonButtons}</div></div></div></section>
<section id="execution-tools" class="mx-auto max-w-6xl px-5 py-20"><p class="text-xs font-black tracking-[.25em] text-amber-400">CAMPUS EXECUTION TOOLS</p><h2 class="mt-4 text-4xl font-black md:text-5xl">From learning to real-world execution.</h2><p class="mt-4 max-w-3xl leading-7 text-stone-400">Use what you learn. Manage resources and business decisions, then discover, promote, or sell opportunities in the community marketplace.</p><div class="mt-10 grid gap-5 md:grid-cols-2"><a href="${businessCalculator}" target="_blank" rel="noopener noreferrer" class="group rounded-3xl border border-amber-400/20 bg-stone-900 p-8 transition hover:border-amber-400/60"><span class="text-xs font-black tracking-[.2em] text-amber-400">MANAGE · MULTIPLY</span><h3 class="mt-3 text-3xl font-black">Business Calculator</h3><p class="mt-3 leading-7 text-stone-400">Turn income, costs, pricing, allocation and business decisions into disciplined management practice.</p><b class="mt-7 inline-block text-amber-400">OPEN BUSINESS CALCULATOR →</b></a><a href="${marketplace}" target="_blank" rel="noopener noreferrer" class="group rounded-3xl border border-amber-400/20 bg-stone-900 p-8 transition hover:border-amber-400/60"><span class="text-xs font-black tracking-[.2em] text-amber-400">EXECUTE · EARN</span><h3 class="mt-3 text-3xl font-black">DELIONARYO Marketplace</h3><p class="mt-3 leading-7 text-stone-400">Promote affiliate products, showcase member-owned products and services, and build real-world execution experience.</p><b class="mt-7 inline-block text-amber-400">OPEN MARKETPLACE →</b></a></div><div class="mt-6 rounded-2xl border border-white/10 bg-black/20 p-6 text-center"><b class="text-amber-400">LEARN → EXECUTE → EARN → MULTIPLY → STEWARD</b><p class="mt-2 text-sm text-stone-400">The Learning Campus connects knowledge to action instead of ending at graduation.</p></div></section>
<section id="store" class="mx-auto max-w-6xl px-5 py-20"><div class="rounded-3xl border border-amber-400/20 bg-stone-900 p-8"><p class="text-xs font-black tracking-[.25em] text-amber-400">DELIONARYO EBOOK STORE</p><h2 class="mt-4 text-4xl font-black">From Survival to Stability</h2><button id="paid-buy" class="mt-6 rounded-xl bg-amber-400 px-6 py-4 font-black text-stone-950">BUY SECURELY WITH PAYMONGO →</button></div></section><section id="social-channels" class="border-t border-white/10 p-10 text-center"><div class="flex justify-center gap-5"><a href="${youtube}" target="_blank">YOUTUBE</a><a href="${tiktok}" target="_blank">TIKTOK</a><a href="${facebook}" target="_blank">FACEBOOK</a></div></section><footer class="border-t border-white/10 px-5 py-8 text-center text-sm text-stone-500">© 2026 DELIONARYO · Transformation through knowledge, execution and stewardship.</footer></main>`;
document.querySelector<HTMLButtonElement>('#paid-buy')?.addEventListener('click',()=>{window.location.href=pay});
document.querySelectorAll<HTMLButtonElement>('[data-video-index]').forEach(button=>button.addEventListener('click',()=>{const lesson=lessons[Number(button.dataset.videoIndex)];if(!lesson)return;const player=document.querySelector<HTMLIFrameElement>('#learning-player');const label=document.querySelector<HTMLElement>('#lesson-label');const title=document.querySelector<HTMLElement>('#lesson-title');if(player)player.src=`https://www.youtube-nocookie.com/embed/${lesson.id}?rel=0&playsinline=1&autoplay=1`;if(label)label.textContent=lesson.label;if(title)title.textContent=lesson.title}));
document.querySelectorAll<HTMLButtonElement>('[data-complete]').forEach(button=>button.addEventListener('click',()=>{const day=button.dataset.complete!;const state=JSON.parse(localStorage.getItem('delionaryo-week')||'{}') as Record<string,boolean>;state[day]=!state[day];localStorage.setItem('delionaryo-week',JSON.stringify(state));button.textContent=state[day]?'✓ COMPLETED':'MARK COMPLETE';button.closest('.journey-card')?.classList.toggle('completed',state[day])}));