const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char] || char));

const portal = document.createElement('section');
portal.id = 'ai-portal';
portal.className = 'ai-portal-section border-y border-amber-400/20';
portal.innerHTML = `
  <div class="mx-auto max-w-6xl px-5 py-20">
    <div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
      <div>
        <p class="text-xs font-black tracking-[.25em] text-amber-400">DELIONARYO AI COMMAND PORTAL</p>
        <h2 class="mt-4 text-4xl font-black md:text-5xl">One command center for the Video Factory.</h2>
        <p class="mt-4 max-w-3xl text-lg leading-8 text-stone-400">Research products, create production records, and hand each Product ID to the next agent without leaving the portal.</p>
      </div>
      <div id="agent-status" class="portal-status portal-status-pending"><span class="portal-dot"></span><span>AGENT CONNECTION: NOT CONFIGURED</span></div>
    </div>

    <div class="mt-10 grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
      <div class="portal-panel">
        <div class="portal-panel-head"><div><span class="portal-kicker">STEP 01</span><h3>Product Research Agent</h3></div><span class="portal-badge">ACTIVE MODULE</span></div>
        <form id="research-form" class="mt-6 space-y-5">
          <div>
            <label for="product-input">Product name or exact product URL</label>
            <textarea id="product-input" rows="3" required placeholder="Example: Lavalier microphone\nhttps://vt.tiktok.com/..." class="portal-input"></textarea>
          </div>
          <div class="grid gap-4 sm:grid-cols-2">
            <div><label for="platform-input">Platform</label><select id="platform-input" class="portal-input"><option>TikTok Shop Affiliate</option><option>TikTok</option><option>Shopee Affiliate</option><option>Other</option></select></div>
            <div><label for="link-input">Affiliate/product link (optional)</label><input id="link-input" class="portal-input" placeholder="https://..." /></div>
          </div>
          <button id="research-btn" type="submit" class="portal-primary"><span>RESEARCH PRODUCT</span><span>→</span></button>
        </form>
        <div id="research-feedback" class="portal-feedback hidden"></div>
      </div>

      <div class="portal-panel">
        <div class="portal-panel-head"><div><span class="portal-kicker">PIPELINE</span><h3>Production sequence</h3></div></div>
        <div class="portal-pipeline mt-6">
          <div class="portal-pipeline-item active"><span>01</span><div><b>Product Research</b><small>Research + Product ID + verification</small></div></div>
          <div class="portal-pipeline-item"><span>02</span><div><b>Script Agent</b><small>Storyboard + dialogue + prompts</small></div></div>
          <div class="portal-pipeline-item"><span>03</span><div><b>Image Production</b><small>Scene images → Supabase</small></div></div>
          <div class="portal-pipeline-item"><span>04</span><div><b>GenV</b><small>Manual 10-second image-to-video</small></div></div>
          <div class="portal-pipeline-item"><span>05</span><div><b>Video Factory</b><small>Assembly → final → upload</small></div></div>
        </div>
      </div>
    </div>

    <div id="research-result" class="portal-panel mt-6 hidden">
      <div class="portal-panel-head"><div><span class="portal-kicker">LATEST RESULT</span><h3>Product research record</h3></div><span id="result-status" class="portal-badge">READY</span></div>
      <div id="result-grid" class="mt-6 portal-result-grid"></div>
    </div>

    <div class="mt-8 grid gap-4 sm:grid-cols-3">
      <div class="portal-mini"><span>PRODUCT ID</span><b>Generated by n8n</b><small>Every product gets a unique production identity.</small></div>
      <div class="portal-mini"><span>STORAGE</span><b>Supabase</b><small>Images and videos remain organized by production record.</small></div>
      <div class="portal-mini"><span>CONTROL</span><b>ChatGPT + Portal</b><small>Use the portal as the operational command center.</small></div>
    </div>
  </div>
`;

const mountPortal = () => {
  const app = document.querySelector<HTMLDivElement>('#app');
  if (!app || document.querySelector('#ai-portal')) return;
  const footer = app.querySelector('footer');
  if (footer) footer.before(portal); else app.appendChild(portal);

  const nav = app.querySelector('nav div div');
  if (nav && !nav.querySelector('[href="#ai-portal"]')) {
    const link = document.createElement('a');
    link.href = '#ai-portal';
    link.textContent = 'AI PORTAL';
    link.className = 'ai-portal-nav-link';
    nav.appendChild(link);
  }

  const status = portal.querySelector<HTMLElement>('#agent-status');
  const feedback = portal.querySelector<HTMLElement>('#research-feedback');
  const result = portal.querySelector<HTMLElement>('#research-result');
  const resultGrid = portal.querySelector<HTMLElement>('#result-grid');
  const button = portal.querySelector<HTMLButtonElement>('#research-btn');
  const form = portal.querySelector<HTMLFormElement>('#research-form');
  const productInput = portal.querySelector<HTMLTextAreaElement>('#product-input');
  const platformInput = portal.querySelector<HTMLSelectElement>('#platform-input');
  const linkInput = portal.querySelector<HTMLInputElement>('#link-input');

  const setFeedback = (message: string, type: 'ok' | 'error' | 'info') => {
    if (!feedback) return;
    feedback.className = `portal-feedback portal-feedback-${type}`;
    feedback.textContent = message;
  };

  const setStatus = (message: string, type: 'ok' | 'error' | 'pending') => {
    if (!status) return;
    status.className = `portal-status portal-status-${type}`;
    status.innerHTML = `<span class="portal-dot"></span><span>${escapeHtml(message)}</span>`;
  };

  // A lightweight health probe tells the user whether the portal backend is deployed.
  fetch('/api/health', { headers: { Accept: 'application/json' } })
    .then((response) => response.ok ? response.json() : Promise.reject(new Error('health')))
    .then((data) => setStatus(data?.ok ? 'PORTAL BACKEND: ONLINE' : 'PORTAL BACKEND: CHECKING', data?.ok ? 'ok' : 'pending'))
    .catch(() => setStatus('PORTAL BACKEND: OFFLINE', 'error'));

  form?.addEventListener('submit', async (event) => {
    event.preventDefault();
    const product = productInput?.value.trim() || '';
    const platform = platformInput?.value || 'TikTok Shop Affiliate';
    const affiliateLink = linkInput?.value.trim() || '';
    if (!product) return;

    if (button) { button.disabled = true; button.innerHTML = '<span>RESEARCHING…</span><span>⏳</span>'; }
    setFeedback('Sending this product to the Product Research Agent…', 'info');

    try {
      const response = await fetch('/api/product-research', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify({ product, platform, affiliateLink })
      });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data?.error || `Request failed (${response.status})`);

      const record = data?.record || data;
      if (result && resultGrid) {
        const fields: Array<[string, unknown]> = [
          ['Product ID', record.productId], ['Product', record.productName || record.product], ['Category', record.category],
          ['Target Customer', record.targetCustomer], ['Problem Solved', record.problemSolved], ['Selling Points', record.keySellingPoints],
          ['Content Angle', record.contentAngle], ['Affiliate Potential', record.affiliatePotential], ['Affiliate Link', record.affiliateLink || affiliateLink],
          ['Verification', record.verificationNeeded], ['Status', record.status || 'RESEARCHED']
        ];
        resultGrid.innerHTML = fields.map(([label, value]) => `<div class="portal-result-item"><span>${escapeHtml(label)}</span><p>${escapeHtml(String(value ?? 'Not provided'))}</p></div>`).join('');
        result.classList.remove('hidden');
      }
      setStatus('PRODUCT RESEARCH AGENT: CONNECTED', 'ok');
      setFeedback('Research completed and the production record was returned successfully.', 'ok');
    } catch (error) {
      setStatus('PRODUCT RESEARCH AGENT: NOT CONNECTED', 'error');
      setFeedback(error instanceof Error ? error.message : 'Unable to reach the Product Research Agent.', 'error');
    } finally {
      if (button) { button.disabled = false; button.innerHTML = '<span>RESEARCH PRODUCT</span><span>→</span>'; }
    }
  });
};

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mountPortal, { once: true });
else mountPortal();
