type Root = { id:number; poverty:string; wealth:string; question:string; action:string; campus:string; tool:string };
type Evidence = { note?:string; completed?:boolean; updatedAt?:string };

const CAMPUS='https://delionaryo-learning-campus.vercel.app';
const roots:Root[]=[
{id:1,poverty:'Resource Insufficiency & Income Fragility',wealth:'Earning Capacity & Value Creation',question:'How reliably does your current income protect essential needs without repeated emergency borrowing or support?',action:'Build an earning-capacity plan: identify one useful skill or value offer and one realistic income pathway to strengthen over the next 30–90 days.',campus:'Income Capacity & Value Creation',tool:'Income Generator / Marketplace'},
{id:2,poverty:'Financial Capability & Information Gap',wealth:'Financial Intelligence & Decision Quality',question:'How confidently can you track cash flow, understand debt/costs, evaluate business economics, and test financial claims before deciding?',action:'Complete money-flow and financial-intelligence learning, then demonstrate the calculations using your own real numbers.',campus:'Business Financial Intelligence',tool:'Money Flow + Business Calculator'},
{id:3,poverty:'Resource Leakage & Weak Control Systems',wealth:'Resource Control & Productive Allocation',question:'How consistently are incoming resources tracked, allocated to priorities, protected from avoidable leakage, and reviewed?',action:'Establish a weekly money-flow review, priority allocation rules, and a sustainable productive-resource discipline where feasible.',campus:'Sovereign Budget & Flow + DPBS',tool:'Money Flow + Expense Tracker + DPBS'},
{id:4,poverty:'Capability-to-Market & Opportunity Constraint',wealth:'Opportunity Access & Enterprise Execution',question:'How effectively can you connect your skills or offers to employers, customers, marketplaces, tools, networks, or other legitimate opportunities?',action:'Choose one execution channel and produce real market evidence through applications, offers, customer conversations, product/service listings, or equivalent activity.',campus:'Marketplace Execution',tool:'DELIONARYO Marketplace'},
{id:5,poverty:'Behavioral, Psychological & Execution Friction',wealth:'Agency, Discipline & Adaptive Execution',question:'How consistently do you follow through on realistic financial actions, manage triggers, review mistakes, and correct your next decision?',action:'Use a weekly execution tracker and one simple decision rule. Record completion, obstacles, and corrections instead of relying on motivation.',campus:"M.O.N.E.Y'S Transformation + Money Belief Reset",tool:'Weekly Freedom Tracker'},
{id:6,poverty:'Protection, Social-System & Stewardship Fragility',wealth:'Resilience, Stewardship & Legacy Capacity',question:'How well is your progress protected against shocks, fraud, harmful obligations, weak records, household misalignment, and other foreseeable risks?',action:'Identify the most serious vulnerability and complete one protection or mitigation action, then document the remaining risk.',campus:'Purpose Alignment + Wealth Legacy Plan',tool:'Protection / Stewardship Review'}
];

const baselineKey='delionaryo-layer1-root-assessment';
const reassessKey='delionaryo-layer1-root-reassessment';
const evidenceKey='delionaryo-layer1-evidence';
const startedKey='delionaryo-layer1-started';
const scale=['Severe constraint / no system','High constraint / rarely demonstrated','Developing / inconsistent','Functional / usually demonstrated','Strong / consistently demonstrated'];
const read=<T>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}};

export function mountRootTransformation(){
 const host=document.querySelector<HTMLElement>('#root-transformation'); if(!host)return;
 const baseline=read<Record<string,number>>(baselineKey,{});
 const evidence=read<Record<string,Evidence>>(evidenceKey,{});
 host.innerHTML=`<div class="root-shell"><p class="root-kicker">GRADUATION · LAYER 1</p><h2>Root Transformation</h2><p class="root-lead">Survival → Stability Foundation. Your progress is based on diagnosis, execution and evidence—not simply finishing lessons.</p><div class="root-flow">Baseline → Diagnose → Prescribed Path → Execute → Evidence → Reassess → Graduation Review</div><div class="root-tabs"><button class="active" data-root-tab="baseline">1 · BASELINE</button><button data-root-tab="evidence">2 · EVIDENCE LOCKER</button><button data-root-tab="reassess">3 · REASSESS</button></div><div id="root-tab-body"></div><p class="root-note">This is an educational diagnostic. It is not a credit score, clinical test, employment screen, lending decision, or judgment of character. Structural constraints and essential needs must remain visible throughout the process.</p></div>`;
 const render=(tab:string)=>{host.querySelectorAll<HTMLButtonElement>('[data-root-tab]').forEach(b=>b.classList.toggle('active',b.dataset.rootTab===tab));const body=host.querySelector<HTMLElement>('#root-tab-body')!;if(tab==='baseline')renderBaseline(body,baseline);if(tab==='evidence')renderEvidence(body,baseline,evidence);if(tab==='reassess')renderReassessment(body,baseline,evidence);};
 host.querySelectorAll<HTMLButtonElement>('[data-root-tab]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.rootTab!)));
 render('baseline');
}

function assessmentCards(scores:Record<string,number>,prefix:string){return `<div class="root-list">${roots.map(r=>`<article class="root-card"><div class="root-number">0${r.id}</div><div><p class="root-label">POVERTY ROOT</p><h3>${r.poverty}</h3><p class="root-arrow">→ ${r.wealth}</p><p>${r.question}</p><div class="root-scale" data-${prefix}-root="${r.id}">${scale.map((s,i)=>`<button type="button" data-score="${i}" class="${scores[r.id]===i?'selected':''}"><b>${i}</b><span>${s}</span></button>`).join('')}</div></div></article>`).join('')}</div>`}

function bindScores(body:HTMLElement,scores:Record<string,number>,key:string,attr:string){body.querySelectorAll<HTMLButtonElement>(`[${attr}] [data-score]`).forEach(btn=>btn.addEventListener('click',()=>{const wrap=btn.closest<HTMLElement>(`[${attr}]`)!;wrap.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');scores[wrap.getAttribute(attr)!]=Number(btn.dataset.score);localStorage.setItem(key,JSON.stringify(scores));}));}

function renderBaseline(body:HTMLElement,scores:Record<string,number>){
 body.innerHTML=`<div class="root-panel-intro"><h3>Baseline Assessment</h3><p>Score the current condition, not the condition you hope to have. Evidence can be added after the baseline.</p></div>${assessmentCards(scores,'base')}<button id="root-result" class="root-result-btn">BUILD MY PRESCRIBED PATH →</button><div id="root-profile"></div>`;
 bindScores(body,scores,baselineKey,'data-base-root');
 body.querySelector<HTMLButtonElement>('#root-result')?.addEventListener('click',()=>renderProfile(body,scores));
}

function renderProfile(body:HTMLElement,scores:Record<string,number>){
 const profile=body.querySelector<HTMLElement>('#root-profile')!;
 if(roots.some(r=>scores[r.id]===undefined)){profile.innerHTML='<div class="root-profile warning"><b>Complete all six roots first.</b><p>Every root needs a baseline response before a pathway can be generated.</p></div>';return;}
 if(!localStorage.getItem(startedKey))localStorage.setItem(startedKey,new Date().toISOString());
 const ranked=[...roots].sort((a,b)=>scores[a.id]-scores[b.id]);const p=ranked[0];const avg=roots.reduce((n,r)=>n+scores[r.id],0)/roots.length;
 profile.innerHTML=`<div class="root-profile"><p class="root-label">PRESCRIBED PATH · FIRST PRIORITY SIGNAL</p><h3>${p.poverty}</h3><p><b>Build:</b> ${p.wealth}</p><p>${p.action}</p><div class="root-prescription"><div><span>LEARN</span><b>${p.campus}</b></div><div><span>APPLY</span><b>${p.tool}</b></div><div><span>EVIDENCE</span><b>Record one real action and outcome</b></div></div><a class="root-campus-link" href="${CAMPUS}">OPEN LEARNING CAMPUS →</a><div class="root-score-grid">${roots.map(r=>`<div><span>Root ${r.id}</span><b>${scores[r.id]}/4</b></div>`).join('')}</div><p><b>Baseline average:</b> ${avg.toFixed(1)}/4</p><p class="root-note">This is a first-pass priority signal. Urgency, essential-stability impact, structural barriers, dependency and feasibility may change intervention order.</p></div>`;profile.scrollIntoView({behavior:'smooth',block:'center'});
}

function renderEvidence(body:HTMLElement,baseline:Record<string,number>,evidence:Record<string,Evidence>){
 const completeBaseline=!roots.some(r=>baseline[r.id]===undefined);
 body.innerHTML=`<div class="root-panel-intro"><h3>Evidence Locker</h3><p>Record what you actually did and what changed. Do not mark a root complete because you only watched or read the lesson.</p></div>${!completeBaseline?'<div class="root-profile warning"><b>Baseline required first.</b><p>Complete all six baseline roots before building graduation evidence.</p></div>':''}<div class="evidence-grid">${roots.map(r=>`<article class="evidence-card"><p class="root-label">ROOT ${r.id}</p><h3>${r.wealth}</h3><p><b>Expected action:</b> ${r.action}</p><textarea data-evidence-note="${r.id}" placeholder="What did you do? What happened? What evidence do you have?">${escapeHtml(evidence[r.id]?.note||'')}</textarea><label class="evidence-check"><input type="checkbox" data-evidence-done="${r.id}" ${evidence[r.id]?.completed?'checked':''}> I completed a real action and can explain the evidence.</label><small>${evidence[r.id]?.updatedAt?`Last updated: ${new Date(evidence[r.id]!.updatedAt!).toLocaleDateString()}`:'No evidence recorded yet'}</small></article>`).join('')}</div><button id="save-evidence" class="root-result-btn" ${!completeBaseline?'disabled':''}>SAVE EVIDENCE →</button><div id="evidence-status"></div>`;
 body.querySelector<HTMLButtonElement>('#save-evidence')?.addEventListener('click',()=>{roots.forEach(r=>{const note=body.querySelector<HTMLTextAreaElement>(`[data-evidence-note="${r.id}"]`)?.value.trim()||'';const completed=!!body.querySelector<HTMLInputElement>(`[data-evidence-done="${r.id}"]`)?.checked;evidence[r.id]={note,completed,updatedAt:new Date().toISOString()};});localStorage.setItem(evidenceKey,JSON.stringify(evidence));const count=roots.filter(r=>evidence[r.id]?.completed&&evidence[r.id]?.note).length;body.querySelector<HTMLElement>('#evidence-status')!.innerHTML=`<div class="root-profile"><b>${count}/6 evidence areas recorded.</b><p>Graduation is not automatic. Reassessment and review still remain.</p></div>`;});
}

function renderReassessment(body:HTMLElement,baseline:Record<string,number>,evidence:Record<string,Evidence>){
 const reassess=read<Record<string,number>>(reassessKey,{});const evidenceCount=roots.filter(r=>evidence[r.id]?.completed&&evidence[r.id]?.note).length;
 body.innerHTML=`<div class="root-panel-intro"><h3>Reassessment</h3><p>Re-score after an evidence period. The recommended initial window is 30–90 days depending on the intervention.</p></div><div class="graduation-readiness"><div><span>BASELINE</span><b>${roots.every(r=>baseline[r.id]!==undefined)?'Complete':'Incomplete'}</b></div><div><span>EVIDENCE</span><b>${evidenceCount}/6</b></div><div><span>STATUS</span><b>Review Required</b></div></div>${assessmentCards(reassess,'re')}<button id="compare-roots" class="root-result-btn">COMPARE & CHECK READINESS →</button><div id="graduation-result"></div>`;
 bindScores(body,reassess,reassessKey,'data-re-root');
 body.querySelector<HTMLButtonElement>('#compare-roots')?.addEventListener('click',()=>compareForGraduation(body,baseline,reassess,evidence));
}

function compareForGraduation(body:HTMLElement,baseline:Record<string,number>,reassess:Record<string,number>,evidence:Record<string,Evidence>){
 const out=body.querySelector<HTMLElement>('#graduation-result')!;
 if(roots.some(r=>baseline[r.id]===undefined)||roots.some(r=>reassess[r.id]===undefined)){out.innerHTML='<div class="root-profile warning"><b>Both assessments must be complete.</b></div>';return;}
 const evidenceCount=roots.filter(r=>evidence[r.id]?.completed&&evidence[r.id]?.note).length;const improvements=roots.map(r=>({r,delta:reassess[r.id]-baseline[r.id]}));const improved=improvements.filter(x=>x.delta>0).length;const noCritical=roots.every(r=>reassess[r.id]>=1);const evidenceReady=evidenceCount>=1;const capabilityImproved=improved>=1;const ready=noCritical&&evidenceReady&&capabilityImproved;
 out.innerHTML=`<div class="root-profile ${ready?'ready':''}"><p class="root-label">LAYER 1 GRADUATION READINESS</p><h3>${ready?'Ready for Graduation Review':'Continue Building Evidence'}</h3><div class="comparison-grid">${improvements.map(x=>`<div><span>Root ${x.r.id}</span><b>${baseline[x.r.id]} → ${reassess[x.r.id]}</b><small>${x.delta>0?`+${x.delta} improvement`:x.delta===0?'No change':`${x.delta} decline`}</small></div>`).join('')}</div><p><b>Evidence areas:</b> ${evidenceCount}/6 · <b>Roots improved:</b> ${improved}/6</p><p>${ready?'You have met the prototype readiness conditions. This does not automatically award graduation; a full version should verify evidence and create the Stability Plan before recording completion.':'Keep working on the priority root. Graduation should follow demonstrated capability, not pressure to complete a score.'}</p><div class="graduation-gates"><span class="${evidenceReady?'pass':''}">Evidence recorded</span><span class="${capabilityImproved?'pass':''}">At least one root improved</span><span class="${noCritical?'pass':''}">No root remains at severe/no-system level</span></div></div>`;out.scrollIntoView({behavior:'smooth',block:'center'});
}

function escapeHtml(value:string){return value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));}