export default function handler(_req:any,res:any){
  res.setHeader('Content-Type','text/html; charset=utf-8');
  res.setHeader('Cache-Control','public, max-age=300, s-maxage=600');
  res.status(200).send(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<meta name="theme-color" content="#071015"/>
<title>DELIONARYO — Professional Ecosystem Landing</title>
<meta name="description" content="DELIONARYO professional ecosystem landing page."/>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#071015;color:#f7f4ec}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 20% 0,rgba(217,170,60,.13),transparent 35rem),linear-gradient(180deg,#071015,#08141a 60%,#050b0e)}.wrap{width:min(1120px,calc(100% - 32px));margin:auto}.nav{display:flex;align-items:center;justify-content:space-between;padding:22px 0}.brand{display:flex;align-items:center;gap:12px;font-weight:950;letter-spacing:.15em}.mark{width:44px;height:44px;border:1px solid #b68a31;border-radius:14px;display:grid;place-items:center;color:#e0b75c;font-size:22px}.nav a{color:#f7f4ec;text-decoration:none;font-weight:850;border:1px solid rgba(217,170,60,.35);padding:11px 15px;border-radius:11px}.hero{padding:78px 0 54px;display:grid;grid-template-columns:1.2fr .8fr;gap:28px;align-items:center}.eyebrow{color:#d9aa3c;font-weight:900;letter-spacing:.2em;font-size:12px}.hero h1{font-size:clamp(46px,8vw,82px);line-height:.94;letter-spacing:-.045em;margin:18px 0}.hero h1 span{color:#d9aa3c}.lead{font-size:clamp(18px,2.4vw,23px);line-height:1.65;color:#c4ced0;max-width:760px}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:28px}.primary,.secondary{display:inline-block;text-decoration:none;padding:15px 20px;border-radius:13px;font-weight:950}.primary{background:#d9aa3c;color:#0e1215}.secondary{border:1px solid rgba(217,170,60,.45);color:#f4d99e}.panel{border:1px solid rgba(217,170,60,.28);background:rgba(9,24,29,.82);border-radius:24px;padding:24px;box-shadow:0 26px 70px rgba(0,0,0,.28)}.panel small{color:#d9aa3c;font-weight:900;letter-spacing:.15em}.panel h2{margin:10px 0 16px;font-size:26px}.flow{display:grid;gap:10px}.step{display:grid;grid-template-columns:38px 1fr;gap:12px;align-items:start;padding:12px;border-radius:14px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.06)}.num{width:34px;height:34px;border-radius:10px;background:#112126;color:#d9aa3c;display:grid;place-items:center;font-weight:950}.step b{display:block}.step span{display:block;color:#96a7aa;font-size:14px;margin-top:3px;line-height:1.5}.section{padding:44px 0}.section h2{font-size:clamp(30px,5vw,48px);margin:0 0 10px}.section p{color:#aebdc0;line-height:1.7}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:24px}.card{border:1px solid rgba(255,255,255,.08);background:#0b171c;border-radius:18px;padding:20px}.card b{font-size:18px}.card p{margin-bottom:0;font-size:14px}.footer{border-top:1px solid rgba(255,255,255,.08);margin-top:32px;padding:26px 0 34px;color:#809195;font-size:13px;display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}@media(max-width:780px){.hero{grid-template-columns:1fr;padding-top:42px}.cards{grid-template-columns:1fr}.nav{gap:12px}.nav a{font-size:13px}.brand{letter-spacing:.08em}.hero h1{font-size:clamp(44px,14vw,68px)}}
</style>
</head>
<body>
<div class="wrap">
<nav class="nav"><div class="brand"><span class="mark">D</span><span>DELIONARYO</span></div><a href="https://app.gapcreation.space/login">MEMBER LOGIN</a></nav>
<main>
<section class="hero"><div><div class="eyebrow">MIND TO STEWARD · FINANCIAL TRANSFORMATION</div><h1>Learn. Execute.<br><span>Transform.</span></h1><p class="lead">DELIONARYO is a connected transformation ecosystem designed to move people from financial survival toward disciplined execution, income creation, multiplication and responsible stewardship.</p><div class="actions"><a class="primary" href="https://app.gapcreation.space/">ENTER PUBLIC APP →</a><a class="secondary" href="https://app.gapcreation.space/#store">GO TO STORE →</a></div></div><aside class="panel"><small>OFFICIAL ACCESS FLOW</small><h2>From public access to private ecosystem.</h2><div class="flow"><div class="step"><div class="num">1</div><div><b>Public DELIONARYO App</b><span>Explore the public learning and transformation environment.</span></div></div><div class="step"><div class="num">2</div><div><b>Purchase 1 Product</b><span>Choose one DELIONARYO product from the Store.</span></div></div><div class="step"><div class="num">3</div><div><b>Receive Activation Code</b><span>After payment verification, receive your 6-digit activation code.</span></div></div><div class="step"><div class="num">4</div><div><b>Create Your Hub Account</b><span>Use the code to create your DELIONARYO member account.</span></div></div><div class="step"><div class="num">5</div><div><b>Enter Private Apps</b><span>The Integration Hub becomes your portal to the connected private ecosystem.</span></div></div></div></aside></section>
<section class="section"><h2>One ecosystem. Clear progression.</h2><p>The public app introduces the system. A verified purchase creates eligibility for member access. The Integration Hub then becomes the central portal for Learning Campus, Marketplace, Wallet, Library, Nation and execution tools.</p><div class="cards"><article class="card"><b>Learn</b><p>Build financial understanding and transformation principles.</p></article><article class="card"><b>Execute</b><p>Apply learning through connected tools and real marketplace activity.</p></article><article class="card"><b>Steward</b><p>Measure progress, manage resources and multiply responsibly.</p></article></div></section>
</main>
<footer class="footer"><span>© 2026 DELIONARYO</span><span>Education → Execution → Transformation</span></footer>
</div>
</body>
</html>`)
}
